name: "Test Beta Build"

on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install git tool
        run: |
          sudo apt-get update
          sudo apt-get install git
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target homeassistant-samsung-frame-art-beta \
            --docker-hub gijsvdhoven
